apiVersion: v1
kind: Secret
metadata:
  name: pitflow-payment-secrets
  namespace: pitflow
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  MERCADO_PAGO_ACCESS_TOKEN: "${MERCADO_PAGO_ACCESS_TOKEN}"
